### ISSUE TITLE
右边这个滚动条偶尔会到最上面,原因不明,触发条件不明

### ISSUE THREAD

**Issue by lancer-wang** [danbai225/pwl-chat#1]
![image](https://user-images.githubusercontent.com/69783837/147309269-787ed550-2214-4b7e-9f6d-6d53b2c46646.png)

**Comment by danbai225** [comment]
了解，晚上看看

**Comment by lancer-wang** [comment]
顺便说一下,能不能做一个开关,屏蔽领取红包的消息,这个在插件上的刷屏太厉害了
![image](https://user-images.githubusercontent.com/69783837/147325656-91eff645-75d6-4f99-b6bf-0dee1d1c587a.png)

**Comment by danbai225** [comment]
应该解决了。

**Comment by danbai225** [comment]
加了个关闭红包打开消息得命令

**Comment by lancer-wang** [comment]
> 加了个关闭红包打开消息得命令

![image](https://user-images.githubusercontent.com/69783837/147532005-3bc71b2c-9596-4ed2-b889-0a1b91efbc38.png)
输入命令依然显示
