### ISSUE TITLE
还是进度条

### ISSUE THREAD

**Issue by lancer-wang** [danbai225/pwl-chat#3]
进度条有时候会突然跑到这个位置,并没有人在刷屏之类的,间歇性触发
![image](https://user-images.githubusercontent.com/69783837/147800330-6671186c-d44c-4ba8-a4ea-422c732db3fe.png)

**Comment by lancer-wang** [comment]
然后,有时候大量刷屏的时候,滚动条会停留在最上方

**Comment by woshiliuxu** [comment]
＋1

**Comment by danbai225** [comment]
改为进度条自动底部，只有鼠标拖动才能拖上去。
